# Generated by Django 4.1.3 on 2022-12-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('serie', models.CharField(max_length=30, unique=True, verbose_name='Nro de serie')),
                ('tipo_activo', models.CharField(choices=[('0', 'Computador'), ('1', 'Impresora')], max_length=1, verbose_name='Tipo de activo')),
            ],
        ),
    ]
