# Generated by Django 4.1.3 on 2022-12-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(choices=[('1', 'Hardware'), ('2', 'Software')], max_length=15),
        ),
    ]
