# Generated by Django 4.1.3 on 2022-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_tipo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('tipo_activo', models.CharField(choices=[('0', 'computador'), ('1', 'impresora')], max_length=1, verbose_name='Tipo de activo')),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='sistema_operativo',
            field=models.CharField(choices=[('0', 'Windows'), ('1', 'Linux'), ('2', 'Mac')], max_length=1, verbose_name='Sistema operativo'),
        ),
        migrations.AlterField(
            model_name='software',
            name='version_sistema_op',
            field=models.CharField(choices=[('0', 'Windows 7'), ('1', 'windows 8.1'), ('2', 'windows 10'), ('3', 'windows 11'), ('4', 'debian'), ('5', 'ubuntu'), ('6', 'mint'), ('7', 'fedora'), ('8', 'manjaro'), ('9', 'catalina'), ('10', 'sierra'), ('11', 'monterrey'), ('12', 'bigsufr')], max_length=2, verbose_name='Versión sistema operativo'),
        ),
    ]
