# Generated by Django 4.1.3 on 2022-12-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_tipoactivo_alter_software_sistema_operativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='serie',
        ),
        migrations.AddField(
            model_name='tipoactivo',
            name='serie',
            field=models.CharField(default='no tiene serie', max_length=90, verbose_name='Nro de serie'),
        ),
        migrations.AlterField(
            model_name='tipoactivo',
            name='marca',
            field=models.CharField(max_length=60, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='tipoactivo',
            name='tipo_activo',
            field=models.CharField(choices=[('0', 'Computador'), ('1', 'Impresora')], max_length=1, verbose_name='Tipo de activo'),
        ),
        migrations.CreateModel(
            name='RegistroActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo_activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.tipoactivo')),
            ],
        ),
    ]
