# Generated by Django 4.1.3 on 2022-12-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_remove_hardware_marca_remove_hardware_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoactivo',
            name='serie',
            field=models.CharField(max_length=90, unique=True, verbose_name='Nro de serie'),
        ),
    ]
